apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metricjob
  name: metricjob
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricjob
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metricjob
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8745"
    spec:
      containers:
      - name: metricjob
        image: docker.internal.sysdig.com/markwallace/metricjob:6
        ports:
        - containerPort: 8745
          protocol: TCP
          name: prometheus
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8745
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8745
          initialDelaySeconds: 3
          periodSeconds: 30
        env:
        - name: RUN_TIME_IN_SECONDS
          value: "60000"
        - name: COUNTER_NAMES
          value: "apple_grape,banana_nut"
        - name: COUNTER_RATIO
          value: ".9,.25"
        - name: COUNTER_VEC_NAME
          value: "mj_sfbay,mj_chico"
        - name: COUNTER_VEC_LABEL
          value: "aaa_index,aaa_index"
        - name: COUNTER_VEC_CARDINALITY
          value: "8,8"
        - name: COUNTER_VEC_RATIO
          value: ".8,.8"
        - name: GAUGE_VEC_NAME
          value: "sine_alpha,sine_noisy,harmonic_360,harmonic_180,harmonic_90"
        - name: GAUGE_VEC_LABEL
          value: "aaa_index,aaa_index,a,a,a"
        - name: GAUGE_VEC_CARDINALITY
          value: "10,8,10,10,10"
        - name: GAUGE_VEC_MIN
          value: "20,0,0,0,0"
        - name: GAUGE_VEC_MAX
          value: "90,900,100,100,100"
        - name: GAUGE_VEC_NOISE
          value: "0,100,0,0,0"
        - name: GAUGE_VEC_PERIOD_SECONDS
          value: "360,500,360,180,90"
        - name: GAUGE_VEC_PHASE_SHIFT_SECONDS
          value: "36,45,36,36,36"
        - name: JOIN_META
          value: "aaa_meta"
        - name: JOIN_LABEL1
          value: "aaa_index"
        - name: JOIN_LABEL2
          value: "AGreekLetter"
        - name: JOIN_LABEL1_VALUES
          value: "0,1,2,3,4,5,6,7,8,9"
        - name: JOIN_LABEL2_VALUES
          value: "alpha,beta,gamma,delta,epsilon,zêta,êta,thêta,iota,kappa"
          
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 256Mi
      imagePullSecrets:
      - name: metricjob-registry