apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metricjob
  name: metricjob
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricjob
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metricjob
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8745"
    spec:
      containers:
      - name: metricjob
        image: docker.internal.sysdig.com/markwallace/metricjob:5
        ports:
        - containerPort: 8745
          protocol: TCP
          name: prometheus
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8745
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8745
          initialDelaySeconds: 3
          periodSeconds: 30
        env:
        - name: RUN_TIME_IN_SECONDS
          value: "60000"
        - name: COUNTER_NAMES
          value: "apple_grape,banana_nut"
        - name: COUNTER_RATIO
          value: ".9,.25"
        - name: COUNTER_VEC_NAME
          value: "mj_sfbay,mj_chico"
        - name: COUNTER_VEC_LABEL
          value: "aaa_index,aaa_index"
        - name: COUNTER_VEC_CARDINALITY
          value: "8,8"
        - name: COUNTER_VEC_RATIO
          value: ".8,.8"
        - name: GAUGE_VEC_NAME
          value: "sine_alpha,sine_noisy"
        - name: GAUGE_VEC_LABEL
          value: "aaa_index,aaa_index"
        - name: GAUGE_VEC_CARDINALITY
          value: "10,8"
        - name: GAUGE_VEC_MIN
          value: "20,0"
        - name: GAUGE_VEC_MAX
          value: "90,900"
        - name: GAUGE_VEC_NOISE
          value: "0,100"
        - name: GAUGE_VEC_PERIOD_SECONDS
          value: "360,500"
        - name: GAUGE_VEC_PHASE_SHIFT_SECONDS
          value: "36,45"

        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 256Mi
      imagePullSecrets:
      - name: metricjob-registry